// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQgzQf3VbAgxT0TkKLQ4bKDIbxs4qncio',
    appId: '1:568056217224:web:da90e783fb5d89175be93d',
    messagingSenderId: '568056217224',
    projectId: 'fixitbhai-ecc47',
    authDomain: 'fixitbhai-ecc47.firebaseapp.com',
    databaseURL: 'https://fixitbhai-ecc47-default-rtdb.firebaseio.com',
    storageBucket: 'fixitbhai-ecc47.firebasestorage.app',
    measurementId: 'G-ZM6FN44EPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKWWFwvjxybHG2I2-fx7EPPLOjaHT8rtU',
    appId: '1:568056217224:android:afbbe092a19431285be93d',
    messagingSenderId: '568056217224',
    projectId: 'fixitbhai-ecc47',
    databaseURL: 'https://fixitbhai-ecc47-default-rtdb.firebaseio.com',
    storageBucket: 'fixitbhai-ecc47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQr6cxwLT72HtGE-5ZUe7iQO6q1W58ecU',
    appId: '1:568056217224:ios:8473690411d47f3a5be93d',
    messagingSenderId: '568056217224',
    projectId: 'fixitbhai-ecc47',
    databaseURL: 'https://fixitbhai-ecc47-default-rtdb.firebaseio.com',
    storageBucket: 'fixitbhai-ecc47.firebasestorage.app',
    iosBundleId: 'com.example.fixitbhaiiAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQr6cxwLT72HtGE-5ZUe7iQO6q1W58ecU',
    appId: '1:568056217224:ios:8473690411d47f3a5be93d',
    messagingSenderId: '568056217224',
    projectId: 'fixitbhai-ecc47',
    databaseURL: 'https://fixitbhai-ecc47-default-rtdb.firebaseio.com',
    storageBucket: 'fixitbhai-ecc47.firebasestorage.app',
    iosBundleId: 'com.example.fixitbhaiiAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQgzQf3VbAgxT0TkKLQ4bKDIbxs4qncio',
    appId: '1:568056217224:web:d4b3ed6e3d31cf145be93d',
    messagingSenderId: '568056217224',
    projectId: 'fixitbhai-ecc47',
    authDomain: 'fixitbhai-ecc47.firebaseapp.com',
    databaseURL: 'https://fixitbhai-ecc47-default-rtdb.firebaseio.com',
    storageBucket: 'fixitbhai-ecc47.firebasestorage.app',
    measurementId: 'G-TY3WP493N8',
  );
}
